modLoader="javafml" #mandatory
loaderVersion="[4,)" #mandatory (2 is current neoforge version)
license="LGPL v3"
[[mods]] #mandatory
modId="serverpacklocatorutility" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Server Pack Locator Utility mod" #mandatory
credits="cpw" #optional
authors="oriononline" #optional
description='''
Server Pack Locator Utility mod.

This mod is distributed as part of the ServerPackLocator to allow interaction with the game.
'''
[[mixins]]
config="utilitymod.mixin.json"
